### ISSUE TITLE
[BUG] Error Message displayed when saving new operation type

### ISSUE THREAD

**Issue by cashmonger** [aquariumbio/aquarium#417]
**Describe the bug**
When creating an operation type, Aquarium creates code objects for the protocol, documentation, preconditions, and cost model. 

As part of enabling people to run tests from pfish, I added in a step to create a test file (In the operation type controller). The test file is not visible in the Aquarium interface (it’s distinct from the tests under the test tab), but it can be pulled with pfish. 

This is causing an error message to appear when creating a new operation type using the interface. The operation type gets created, but an error message pops up. 

As you can see from the request, there should be an entry for “test” here, but there isn’t. 

**To Reproduce**

1. pull the pfish-compatibility-updates branch and run aquarium.
2. Go to the developer page in Aquarium and hit new to create a new op type.
3. Give the op type a name and hit save. 
4. After getting the error message, refresh the page to see that the new op type was saved.

**Expected behavior**
There should not be an error message. 

**Screenshots**

Error Message
<img width="1287" alt="ErrorMessage" src="https://user-images.githubusercontent.com/25681610/90554083-38808e00-e14a-11ea-96b5-9667adc24231.png">

Created OT
<img width="1228" alt="showadd" src="https://user-images.githubusercontent.com/25681610/90554239-6a91f000-e14a-11ea-9b53-13c0f6e3b7c3.png">

Request
<img width="1111" alt="request" src="https://user-images.githubusercontent.com/25681610/90554257-6fef3a80-e14a-11ea-8df9-95b043e64840.png">

**Comment by marikoja** [comment]
[HAR file of request information](https://drive.google.com/file/d/1qKoUKWK11x8YqemE1r3dteKVwE9esYnV/view?usp=sharing)

![image](https://user-images.githubusercontent.com/31191468/90816090-9050fd80-e2e0-11ea-9a05-f8efa2a1a5c6.png)

![image](https://user-images.githubusercontent.com/31191468/90818671-b9bf5880-e2e3-11ea-97e9-cf697810869e.png)
