### ISSUE TITLE
Aquarium displays entire history of key-value pairs for data associations

### ISSUE THREAD

**Issue by dvnstrcklnd** [aquariumbio/aquarium#418]
**Describe the bug**
When a data association with a given key is updated, the system evidently creates a new row for that key in the database rather than updating the existing row. This is good from a record-keeping perspective, but the system does not remove duplicates when displaying the associations through the GUI. This results in confusion about which value is the correct one for a given key. The problem is particularly salient when iteratively adding provenance to an item, and results in lists of associations like this one:

![image](https://user-images.githubusercontent.com/7586251/90789016-62fe5280-e2d4-11ea-8f83-bbaf92fb646d.png)

**To Reproduce**
Add multiple data associations with the same key to any object.

**Expected behavior**
Following usual conventions for key-value data structures, retrieving data associations for an object should yield no more than one data association for a given key. It should be the one most recently *updated* in the database.

Additionally, when adding data associations through the GUI, it would be good if Aquarium provided a warning when a key is being duplicated / overwritten.

**Comment by dvnstrcklnd** [comment]
@bjkeller @gnomicosuw @marikoja It would be good to fix this with high priority. It is a really big problem when using provenance associations in the context of the COVID protocols.

**Comment by bjkeller** [comment]
I think this is part of a broader problem of being unable to represent the state of an item. You should be able to write a protocol that simply modifies an item without having to worry about provenance being right. 
For provenance, we need to distinguish the state of a well before and after it has been modified, but for the protocol the author should only care about the current state. 

My question is whether we should go ahead and address this root issue, or do the filter?

**Comment by dvnstrcklnd** [comment]
This issue is intended to be independent of what is happening in protocols,
regarding provenance or otherwise. It's confusing to have duplicate
associations for a given key, regardless of how they are generated.

As I indicated, addressing this issue would mask the separate issue that is
happening in the protocol code, but addressing that issue would not fix
this one.

**Comment by dvnstrcklnd** [comment]
Regarding timing, as I indicated I think this is an urgent issue. I also
think it can be addressed with relatively small changes, and the result
would be a more faithful representation of the "current state" of the item.
While I like the idea of addressing the root cause, I don't see that
happening on an acceptable timeline,

**Comment by bjkeller** [comment]
OK, sounds good. 

If I'm understanding correctly, we have two stories here:
1. As a user viewing the data associations for an item, I expect to see the value most recently assigned to a key in order to understand the current state of the item.
2. As a user creating a data association, I want to confirm when the key exists in order to avoid mistakenly changing the displayed state of the item.

Is that correct?

**Comment by dvnstrcklnd** [comment]
Yes

**Comment by marikoja** [comment]
That all makes sense to me, this ticket will address the first story that Ben restated.

**Comment by bjkeller** [comment]
@marikoja Can you make a new issue for story 2 and cross link with this one? 

Also, would be great if you can make sure both are exposed as TODOs on https://github.com/orgs/aquariumbio/projects/1

**Comment by bjkeller** [comment]
Associations are listed in multiple ERB files using calls to `DataAssociator::data_associations`:
- app/views/plans/_sidebar.html.erb:    `<div ng-if="plan.data_associations">`
- app/views/data_associations/_template.html.erb:         `ng-repeat="da in record.data_associations track by $index"`
- app/views/data_associations/_list.html.erb:      `<li ng-repeat="da in parent.data_associations | filter: { key: '!notes' }">`
- app/views/operations/_operation_list.html.erb:            `<li ng-repeat="da in op.data_associations">`
- app/views/operations/_operation_list_short.html.erb:            `<li ng-repeat="da in op.data_associations track by $index">`
- app/views/items/show.html.erb:                 `ng-repeat="da in part.data_associations"`

**Comment by bjkeller** [comment]
I think the solution is to add a `current_value` scope function to `DataAssociation` and use the scope in the queries in `DataAssociator::data_associations`

@gnomicosuw do you have time for this before you go?

**Comment by dvnstrcklnd** [comment]
Note that most data association methods in the API return single keys, but
this may be an accident of building the hash.

**Comment by gnomicosuw** [comment]
@bjkeller - looking at this now and will check something in for us to review shortly. I'm not sure I have a great repro scenario so maybe we can have a quick call to review after I update it

**Comment by gnomicosuw** [comment]
As Devin suggested, every time a key value gets changed it appears a new row is written to the DB. 

To return the latest value for each key it appears we can get the value for each key based on the latest 'id' field fr that key (as opposed to the latest 'updated_at"'field). From a query perspective that is faster and more robust (among other things it is possible, although unlikely, that two records in the DB have the same 'updated_at' value)

As a brute-force alternative we can also simply query for all values and loop through them to get the latest one for each key.  This might be the best solution since I assume there are not that many key-value pairs for each sample.

@bjkeller - do you have a preference?

**Comment by bjkeller** [comment]
Yes, I should look more.  

There is another method `DataAssociator::associations` that builds a hash from the `data_associations`.
It is used in `app/views/operation_types/_test.html.erb`. 
Maybe can just call that.

**Comment by gnomicosuw** [comment]
Yes. That is the method I am looking at!  Wanna zoom quickly and I can show you my ideas?

**Comment by bjkeller** [comment]
There are direct `DataAssociation` queries in



> As Devin suggested, every time a key value gets changed it appears a new row is written to the DB.
> 
> To return the latest value for each key it appears we can get the value for each key based on the latest 'id' field for that key (as opposed to the latest 'updated_at' field). From a query perspective that is faster and more robust (among other things it is possible, although unlikely, that two records in the DB have the same 'updated_at' value)
> 
> As a brute-force alternative we can also simply query for all values and loop through them to get the latest one for each key. This might be the best solution since I assume there are not that many key-value pairs for each sample.
> 
> @bjkeller - do you have a preference?

preference: faster and more robust

**Comment by dvnstrcklnd** [comment]
I think grabbing the latest ID is OK only if you can be sure that rows are
never updated.

**Comment by gnomicosuw** [comment]
I cannot be sure that rows are never updated. In fact I did a quick check in the DB and the timestamps are not always the same. It could be the key is created and then saved (vs updated later) but I do not have enough knowledge of the rest of the system to guarantee that.

For now I suggest just looping through the values.  I can always take another look at it later.

**Comment by bjkeller** [comment]
There are `DataAssociation.where` queries in 
- CollectionsController
- OperationsController
- UploadsController
- Collection

**Comment by bjkeller** [comment]
`CollectionsController::save_data_associations` updates a DataAssociation found by ID, I think this is only called from the collection editor view

**Comment by dvnstrcklnd** [comment]
If this fix covers most ways of accessing the associations, including through Trident, then yes I believe this is what I want.

**Comment by bjkeller** [comment]
I believe trident is using the JsonController to grab `DataAssociator.associations`.  Will verify.
