### ISSUE TITLE
tech-handoff: select all checkbox doesn't refresh

### ISSUE THREAD

**Issue by dvnstrcklnd** [aquariumbio/aquarium#442]
**Describe the bug**
The select all checkbox doesn't refresh when switching between operation types

**To Reproduce**
1. Select pending operations of one operation type
2. Check select all checkbox
3. Select pending operations of a different operation type 

**Expected behavior**
The select all box remains checked, probably should be unchecked.

**Comment by bjkeller** [comment]
fixed by https://github.com/aquariumbio/aquarium/commit/a477ed14b7ca042424a9e06efc3baa1e2d71f680
