### ISSUE TITLE
tech-handoff: assignment radio button doesn't clear

### ISSUE THREAD

**Issue by dvnstrcklnd** [aquariumbio/aquarium#443]
**Describe the bug**
The assignment radio button doesn't clear after the job is unassigned

**To Reproduce**
1. Assign a job to a technician
2. Unassign the job
3. Click on the assign button again

**Expected behavior**
The radio button remains clicked, seems like they should all be unclicked when the assignment is cancelled.

**Comment by bjkeller** [comment]
fixed by https://github.com/aquariumbio/aquarium/commit/84d7be59948352135935d1b897ad79bccf2c548c
