### ISSUE TITLE
[BUG] v3 Sign in does not handle special characters

### ISSUE THREAD

**Issue by marikoja** [aquariumbio/aquarium#456]
**Describe the bug**
v3 sign in does not allow special characters

**To Reproduce**
1. Go to '/'
2. Enter username and password with special character
3. Click on 'SIGN IN'

**Expected behavior**
Allow sign in for all valid username/password combinations

**Comment by bjkeller** [comment]
@marikoja this is not linked to a PR or a commit. Can you confirm which PR it was in?
