### ISSUE TITLE
Run Aquarium on a cloud service

### ISSUE THREAD

**Issue by imderek** [aquariumbio/aquarium#460]
On the [Aquarium site](https://www.aquarium.bio/?category=Getting%20Started&content=Installation) under Installation it says "If you want to: Run Aquarium on a cloud service: **Contact us**." but unfortunately there's no contact information anywhere on the site.

Can anyone provide contact info for the appropriate party and/or details for hosting Aquarium in the cloud (we primarily use Heroku)?

Thanks!

**Comment by bjkeller** [comment]
@imderek I was being overly ambitious when I wrote that, so I've removed the note.  But, I'll send you an email.
