### ISSUE TITLE
Tech-Handoff: Cannot preview completed jobs [BUG]

### ISSUE THREAD

**Issue by malloc3** [aquariumbio/aquarium#469]
**Please identify the user roles that your feature request relates to?**
Lab Managers, Protocol Development

**What is the task you want to perform?**
In previous version of Aquarium manager page, Under 'Error' and 'Done' you could navigate to the job and see exactly how it was performed.    The functionality no longer exists (or I could not find it).     This functionality is incredibly helpful for debugging protocols and for reviewing jobs etc.

**What is the goal you want to achieve with the feature?**
I need to be able to preview jobs that have been completed (either "Error" or "Done") and walk through the step by step views that the technician saw.

**Comment by bjkeller** [comment]
The job header is not included for done and error and so the job link is missing

**Comment by bjkeller** [comment]
Also affected by #458

**Comment by marikoja** [comment]
@malloc3 Confirming the ask is to put the jobs column back into the table only when  **error**ed or **done** operations?
<img width="1792" alt="Screen Shot 2020-12-02 at 12 43 41 PM" src="https://user-images.githubusercontent.com/31191468/100918929-bd47ab80-349e-11eb-9e07-b977c01ca30a.png">
<img width="1792" alt="Screen Shot 2020-12-02 at 12 41 55 PM" src="https://user-images.githubusercontent.com/31191468/100918991-d2bcd580-349e-11eb-8ae2-02acd64eddbc.png">

**Comment by malloc3** [comment]
Yes.   Or equivalent functionality.
