### ISSUE TITLE
Tech-Handoff: Relax permissions on marking item as deleted

### ISSUE THREAD

**Issue by bjkeller** [aquariumbio/aquarium#471]
A non-admin user should be able to mark an item as deleted.

This appears to be handled in ERB files using the `mark_as_deleted` method. I see a call in `app/views/items/_template.html.erb` that is guarded by a check of `current_user.is_admin`, but should check for others

**Comment by marikoja** [comment]
@bjkeller to clarify we want to allow all users to mark items as deleted, ie remove the inventory location?

**Comment by dvnstrcklnd** [comment]
Yes, I think that's what we agreed to.
