### ISSUE TITLE
Implement nginx routing to enable one hybrid v2 / v3 app

### ISSUE THREAD

**Issue by gnomicosuw** [aquariumbio/aquarium#594]
This is secondary priority for now. In the meantime v2 and v3 can live "side-by-side" and point to the same database.

- [ ] have v3 urls point to v3 and v2 urls point to v2 (is this part of docker-compose?)
- [ ] hardcode "v3-specific" relative URLs in v2 app to point to absolute v3 URLs
- [ ] hardcode "v2-specific" relative URLs in v3 app to point to absolute v2 URLs

**Comment by bjkeller** [comment]
Replaced by #608, #609, and #610
